_type: export
__export_format: 4
__export_date: 2024-03-01T18:21:08.642Z
__export_source: insomnia.desktop.app:v8.6.1
resources:
  - _id: req_b5a4c1680ab24410b7ce7b259d96219c
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709316443156
    created: 1709316420227
    url: "{{ _.baseUrl }}/api/swagger-ui/index.html#/"
    name: Swagger
    description: ""
    method: GET
    body: {}
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/8.6.1
    authentication: {}
    metaSortKey: -1709316420227
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    parentId: null
    modified: 1709149480550
    created: 1709149480550
    name: em_test.yaml
    description: ""
    scope: design
    _type: workspace
  - _id: req_6121ccdca15749da8c0bf52ea9292fea
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709313144571
    created: 1709244975918
    url: "{{ _.baseUrl }}/api/auth/refresh"
    name: Refreshing token
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: >-
        {
        	"_comment": "Для обновления токенов нужно вставить ниже refreshToken, который дается при входе в систему, но, главное условие - нужно заходить в аккаунт добавляя UUID deviceToken в тело запроса",
        	"refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huX2RvZTEyMzQ1NiIsImV4cCI6MTcwOTg0OTk1MSwidXNlcklkIjoiMSIsImRldmljZUlkIjoiMSIsInJvbGUiOiJVU0VSIn0.exWQJ7mh6bkjCebO7sSiUq9QhGAOoRYOzS_r1Z7Motq5yKsFyqpwg91bTLdMmG6wyGawP_Y67C_OB5Z6CJdtag"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: ""
    metaSortKey: -1709244975918
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_8477076e489e40609d892a897aa74247
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709313324848
    created: 1709233000568
    url: "{{ _.baseUrl }}/api/wallet/transfer"
    name: Transfer to another client
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: >-
        {
        	"_comment": "Зарегистрируйте нового пользователя и вставьте его юзернейм в recipientUsername",
        	"recipientUsername": "anotherClient",
        	"amount": 100
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.accessToken }}"
    metaSortKey: -1709233000568
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_2ebefaa1c9be4300b82c9241632a4b23
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709317173014
    created: 1709220805681
    url: "{{ _.baseUrl
      }}/api/clients/search?name=Anton&phone=+79081503325&email=pestrikv1337@gm\
      ail.com&page=1&size=10"
    name: Search clients by filters
    description: ""
    method: GET
    body:
      mimeType: application/json
      text: |-
        {
        	"_comment": "Доступные фильтры: birth, phone, name, email"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.accessToken }}"
    metaSortKey: -1709220805681
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_1b399bcb8a204de480ff80ddbb7cba49
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709313278895
    created: 1709215467278
    url: "{{ _.baseUrl }}/api/clients/client/delete-phone"
    name: Delete client phone number
    description: ""
    method: DELETE
    body:
      mimeType: application/json
      text: |-
        {
        	"number": "+79081503325"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.accessToken }}"
    metaSortKey: -1709203400719
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_1966a2b8a07048d6828800c79166d71c
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709313258732
    created: 1709215490928
    url: "{{ _.baseUrl }}/api/clients/client/delete-email"
    name: Delete client email
    description: ""
    method: DELETE
    body:
      mimeType: application/json
      text: |-
        {
        	"address": "pestrikv1337@gmail.com"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.accessToken }}"
    metaSortKey: -1709203053697.5
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_14969d43f91c49b1b560e04837688850
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709313239802
    created: 1709204666138
    url: "{{ _.baseUrl }}/api/clients/client/change-phone"
    name: Change client phone number
    description: ""
    method: PUT
    body:
      mimeType: application/json
      text: |-
        {
        	"oldPhone": "+79081503324",
        	"newPhone": "+77017141660"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.accessToken }}"
    metaSortKey: -1709189223018.5
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_3643e4a94c584c7685ed9f22695d6386
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709313197781
    created: 1709204676659
    url: "{{ _.baseUrl }}/api/clients/client/change-email"
    name: Change client email
    description: ""
    method: PUT
    body:
      mimeType: application/json
      text: |-
        {
        	"oldEmail": "pestirkv13777@gmail.com",
        	"newEmail": "antonpestrikov@gmail.com"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.accessToken }}"
    metaSortKey: -1709177127447
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_21625ac4f82841729b7668072a8a0635
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709313188238
    created: 1709201318590
    url: "{{ _.baseUrl }}/api/clients/client/add-email"
    name: Add client email
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"address": "oluwu123@gmail.com"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.accessToken }}"
    metaSortKey: -1709171079661.25
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_ad9a319aa5a4431daddd668142cdf54b
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709313169409
    created: 1709204094762
    url: "{{ _.baseUrl }}/api/clients/client/add-phone"
    name: Add client phone number
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"number": "+77778127015"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.accessToken }}"
    metaSortKey: -1709165031875.5
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_4c72f66a2df64ce08ea6875665f6e03c
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709237299448
    created: 1709152936304
    url: "{{ _.baseUrl }}/api/clients/client"
    name: Get client details
    description: ""
    method: GET
    body: {}
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.accessToken }}"
    metaSortKey: -1709152936304
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_4823d064a125443193545f61da3426e9
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709317234569
    created: 1709149590349
    url: "{{ _.baseUrl }}/api/auth/signin"
    name: Sign in
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"username": "eridium",
        	"password": "eridium123",
        	"_deviceToken": "90cc66a2-6d25-4edc-90e7-245fa209a22e"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication: {}
    metaSortKey: -1709149590349
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_0d125ca204a04219a72ce317f15d7657
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709316885763
    created: 1709149495132
    url: "{{ _.baseUrl }}/api/auth/signup"
    name: Sign up
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        
        {
          "firstName": "Anton",
          "lastName": "Pestrikov",
          "patronymic": "Sergeevich",
          "username": "eridium",
          "password": "eridium123",
          "initialBalance": 1000,
          "phones": [
            {
              "number": "+79081503324"
            },
            {
              "number": "+79081503325"
            }
          ],
          "emails": [
            {
              "address": "pestrikv1337@gmail.com"
            },
            {
              "address": "pestrikv123@gmail.com"
            }
          ],
          "birth": "2003-22-02"
        }
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication: {}
    metaSortKey: -1709149495132
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: env_5bcbe767686e58aaa5af783e4550414d900d51d5
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709317218949
    created: 1709149480554
    name: Base Environment
    data:
      baseUrl: http://localhost:8080
      accessToken: accessToken_needs_here
    dataPropertyOrder:
      "&":
        - baseUrl
        - accessToken
    color: null
    isPrivate: false
    metaSortKey: 1709149480554
    _type: environment
  - _id: jar_5bcbe767686e58aaa5af783e4550414d900d51d5
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709149480554
    created: 1709149480554
    name: Default Jar
    cookies: []
    _type: cookie_jar
  - _id: spc_191a7a1db5dc417ca038f17ffde359c9
    parentId: wrk_cb7605c6fd2c4fef93ece85ceb833c45
    modified: 1709234462136
    created: 1709149480551
    fileName: em_test.yaml
    contents: ""
    contentType: yaml
    _type: api_spec
